/**
* Copyright (c) 2026 Sergio Hernandez. All rights reserved.
*
*  Licensed under the Apache License, Version 2.0 (the "License").
*  You may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/**
 * Help content hooks (spec 26). Content is static: public/help/manifest.json
 * (generated by scripts/build-help.mjs) plus one Markdown file per topic per
 * language, fetched lazily on first open and cached forever (the ?v= content
 * hash busts caches across releases).
 *
 * The SPA fallback serves index.html with HTTP 200 for missing files, so a
 * miss is detected by content, not status: an HTML body means "not found".
 * A missing topic retries in English and finally resolves with markdown:null
 * (never throws — the dialog degrades to the index view with a notice, and
 * the global query-cache error toast stays out of it).
 */

import { useQuery } from '@tanstack/react-query';

export interface HelpTopicI18n {
  title: string;
  description: string;
  tags: string[];
}

export interface HelpTopicMeta {
  id: string;
  category: string;
  order: number;
  screens: string[];
  related: string[];
  featureKey: string | null;
  hash: string;
  i18n: Record<string, HelpTopicI18n>;
}

export interface HelpManifest {
  version: string;
  languages: string[];
  categories: { id: string; order: number }[];
  topics: HelpTopicMeta[];
}

export interface HelpTopicContent {
  /** Markdown body (frontmatter stripped), or null when missing in every language. */
  markdown: string | null;
  /** Language the content was actually served in (EN fallback on a stale cache). */
  resolvedLang: string;
}

export const helpKeys = {
  all: ['help'] as const,
  manifest: () => [...helpKeys.all, 'manifest'] as const,
  topic: (lang: string, id: string) => [...helpKeys.all, 'topic', lang, id] as const,
};

/** Normalize an i18next language tag to a manifest language (es-CO → es), EN fallback. */
export function normalizeHelpLanguage(language: string, supported: string[]): string {
  const base = (language || 'en').toLowerCase().split('-')[0];
  return supported.includes(base) ? base : 'en';
}

function looksLikeHtml(contentType: string | null, body: string): boolean {
  if (contentType && contentType.includes('text/html')) return true;
  const head = body.trimStart().slice(0, 15).toLowerCase();
  return head.startsWith('<!doctype') || head.startsWith('<html');
}

/** Fetch a static file; null when missing (404 or the SPA index.html fallback). */
async function fetchStatic(url: string): Promise<string | null> {
  const response = await fetch(url);
  if (!response.ok) return null;
  const body = await response.text();
  return looksLikeHtml(response.headers.get('content-type'), body) ? null : body;
}

/** Drop the YAML frontmatter block — the runtime renders the body only. */
export function stripFrontmatter(markdown: string): string {
  const match = /^---\r?\n[\s\S]*?\r?\n---\r?\n/.exec(markdown);
  return match ? markdown.slice(match[0].length) : markdown;
}

export async function fetchHelpManifest(): Promise<HelpManifest> {
  const body = await fetchStatic('/help/manifest.json');
  if (body === null) {
    throw new Error('Help manifest is not available');
  }
  return JSON.parse(body) as HelpManifest;
}

export async function fetchHelpTopic(
  lang: string,
  topic: Pick<HelpTopicMeta, 'id' | 'hash'>
): Promise<HelpTopicContent> {
  const candidates = lang === 'en' ? ['en'] : [lang, 'en'];
  for (const candidate of candidates) {
    const body = await fetchStatic(`/help/${candidate}/${topic.id}.md?v=${topic.hash}`);
    if (body !== null) {
      return { markdown: stripFrontmatter(body), resolvedLang: candidate };
    }
  }
  return { markdown: null, resolvedLang: lang };
}

export function useHelpManifest(options: { enabled?: boolean } = {}) {
  return useQuery({
    queryKey: helpKeys.manifest(),
    queryFn: fetchHelpManifest,
    staleTime: Infinity,
    enabled: options.enabled ?? true,
  });
}

export function useHelpTopic(lang: string, topic: HelpTopicMeta | undefined) {
  return useQuery({
    queryKey: helpKeys.topic(lang, topic?.id ?? ''),
    queryFn: () => fetchHelpTopic(lang, topic as HelpTopicMeta),
    staleTime: Infinity,
    enabled: !!topic,
  });
}
