<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>TrackHubCommon.Application</PackageId>
    <Authors>Sergio Hernandez</Authors>
    <Company>TBD</Company>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL.Client" />
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="HotChocolate" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Domain\Common.Domain.csproj" />
  </ItemGroup>
</Project>